### ISSUE TITLE
Cannot query field "Content" on type "Query". Did you mean "_Content"?"

### ISSUE THREAD

**Issue by rsudworth** [remkoj/optimizely-saas-starter#2]
I'm trying to get into Optimizely SaaS, but found the code at https://github.com/episerver/cms-saas-vercel-demo a little too complete to learn and build from, so I've been using this as my starter instead. Thank you for all the effort that has gone into these tools to use SaaS.

After following the read me instructions, I got this error:

> Cannot query field "Content" on type "Query". Did you mean "_Content"?"

I found it was coming from [src/app/[[...path]]/page.tsx](https://github.com/remkoj/optimizely-saas-starter/blob/main/src/app/%5B%5B...path%5D%5D/page.tsx), which in turn calls a graph query from https://github.com/remkoj/optimizely-dxp-clients/blob/main/packages/optimizely-cms-nextjs/src/cms-page/data.ts. I was able to replicate the same error in my Saas instance and fix it by swapping to `_Content`.

I tried to fix it by updating the referenced pakages to *-pre5, but they still had the same issue.

I noticed that the larger cms-saas-vercel-demo codebase doesn't use the same query and instead page.tsx uses the graph functions inside the site code (which I think are generated?). Based on this, I was able to get my optimizely-saas-starter site going with the following page.tsx:

```
import { CmsPage as OptimizelyCmsPage } from "@remkoj/optimizely-cms-nextjs";
import getFactory from "@/components/factory";
import { getContentByPath } from "@/gql/functions";

// const { CmsPage, generateMetadata, generateStaticParams } = OptimizelyCmsPage.createPage(getFactory(), {})
const { generateMetadata, generateStaticParams, CmsPage } =
  OptimizelyCmsPage.createPage(getFactory(), {
    getContentByPath:
      getContentByPath as OptimizelyCmsPage.GetContentByPathMethod,
  });

// Configure the Next.JS route handling for the pages
export const dynamic = "force-static"; // Make sure we cache pages
export const dynamicParams = true; // Allow new pages to be resolved without rebuilding the site
export const revalidate = false; // Keep the cache untill manually revalidated using the Webhook
export const fetchCache = "default-cache"; // Cache fetch results by default

// Export CMS Page
export { generateMetadata, generateStaticParams };
export default CmsPage;
```

I'm not sure if the Optimizey graph schema has changed, this is a bug, or all of this code Optimizely have suggested we use to inboard with Saas is still a work in progress, but I though it couldn't hurt to raise the issue.

**Comment by moel-levo** [comment]
You are right, the base types were changed a while ago and are now prefixed with "_".

![image (4)](https://github.com/remkoj/optimizely-saas-starter/assets/110657375/38ba1a58-5bf4-4088-8ec0-8530af29c1b8)

**Comment by jamestran1** [comment]
Here is the documentation about Saas Content Types: https://docs.developers.optimizely.com/content-management-system/v1.0.0-CMS-SaaS/docs/content-base-types

**Comment by jamestran1** [comment]
I think this start is fit with traditional CMS or the Paas version, not the Saas CMS.

**Comment by remkoj** [comment]
This starter works with and is intended for the SaaS version of Optimizely CMS, I have updated the dependencies today to 2.0.1 which should resolve all bugs (including the one above) that I'm aware of. Please re-open an issue if the problem persists
